
version : "3.7"

services :  
    
    mysql_prueba:
        container_name: "mysql_prueba"
        image: mysql:5.7
        restart : always
        environment:
            MYSQL_ROOT_PASSWORD: "pass_nsr*"
            MYSQL_DATABASE: "dbvehiculo"
            MYSQL_USER: "mysql"
            MYSQL_PASSWORD: "pass_nsr*"
    
        
        ports:
            - "3306:3306"
            

        
    app:
        restart : always
        build: .
        working_dir: /vehiculo
       
        
        ports :
            - 8035:8035
        
            
        depends_on:
            - mysql_prueba
        
        environment: # Pass environment variables to the service
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql_prueba:3306/dbvehiculo
            SPRING_DATASOURCE_USERNAME : mysql
            SPRING_DATASOURCE_PASSWORD : pass_nsr*